# -*- coding: utf-8 -*-
"""Insurance-Risk-Pricing-Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_yqbkpv0jhf1bZc2vTpJZwXRsmbCaVjV
"""

import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/Insurance Loss Severity & Risk-Based Pricing Model/train.csv")
df.head()

df.isnull().sum()

df = pd.get_dummies(df, drop_first=True)
df["loss"].describe()

import matplotlib.pyplot as plt

plt.hist(df["loss"], bins=75, edgecolor="black")
plt.title("Distribution of Insurance Loss")
plt.xlabel("Loss Amount")
plt.ylabel("Frequency")

plt.show()

import matplotlib.pyplot as plt
import numpy as np

df["log_loss"] = np.log(df["loss"])
plt.hist(df["log_loss"], bins=50, edgecolor="black")

plt.title("Distribution of Log-Transformed Loss")
plt.xlabel("Log(Loss)")
plt.ylabel("Frequency")

plt.show()

df_encoded = pd.get_dummies(df, drop_first=True)
df.shape
df_encoded.shape

X = df_encoded.drop(["loss", "log_loss", "id"], axis=1)
y = df_encoded["log_loss"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(
    n_estimators=20,
    max_depth=10,
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

rf_preds = model.predict(X_test)

from sklearn.metrics import mean_squared_error, r2_score

rf_mse = mean_squared_error(y_test, rf_preds)
rf_r2 = r2_score(y_test, rf_preds)

print("Random Forest MSE:", rf_mse)
print("Random Forest R2:", rf_r2)

df = df.copy()

df["risk_level"] = pd.qcut(df["loss"], 3, labels=["Low", "Medium", "High"])

def pricing_model(loss):
    if loss < 2000:
        return loss * 1.1
    elif loss < 8000:
        return loss * 1.3
    else:
        return loss * 1.6

df["estimated_premium"] = df["loss"].apply(pricing_model)

df.groupby("risk_level", observed=False)["estimated_premium"].mean()

df.groupby("risk_level", observed=False)["loss"].mean().plot(kind="bar")

plt.title("Average Insurance Loss by Risk Level")
plt.xlabel("Risk Level")
plt.ylabel("Average Loss")
plt.xticks(rotation=0)
plt.show()

df.groupby("risk_level", observed=False)["estimated_premium"].mean().plot(kind="bar")

plt.title("Estimated Premium by Risk Level")
plt.xlabel("Risk Level")
plt.ylabel("Average Premium")
plt.xticks(rotation=0)
plt.show()

import numpy as np

errors = np.abs(y_test - rf_preds)

plt.scatter(y_test, rf_preds, c=errors, cmap="coolwarm", alpha=0.5)
plt.colorbar(label="Prediction Error")

plt.title("Predicted vs Actual Log Loss (Colored by Error)")
plt.xlabel("Actual Log Loss")
plt.ylabel("Predicted Log Loss")
plt.show()

import pandas as pd

importance = pd.Series(model.feature_importances_, index=X.columns)
importance.sort_values(ascending=False).head(10).plot(kind="barh")

plt.title("Top 10 Important Features")
plt.xlabel("Importance Score")
plt.show()